### PR TITLE
everything is fixed 

### PR DESCRIPTION
**Pull request by abidhazratzai**
please let me know if anything is needed

### CODE REVIEW

**Review by abidhazratzai — COMMENTED** [review]
new web element that was giving error is been fixed

**Comment by sagcatas** [comment]
looks good, i run your branch it worked good , let see

**Review by sagcatas — COMMENTED** [review]
it looks ok

**Review by sagcatas — APPROVED** [review]

**Review by sagcatas — APPROVED** [review]
looks ok

**Review by sagcatas — APPROVED** [review]

**Review by sagcatas — APPROVED** [review]

**Review by sagcatas — APPROVED** [review]

**Review by sagcatas — APPROVED** [review]

**Review by Anriverd — CHANGES_REQUESTED** [review]
I see you located  Configure_menu. Can you change capital letter to lowercase letter?
I see you renamed submit button to Login button. It is good. Can you also change it to lowercase letter? it is best practice to name elements with first lowercase letter. Than we can merge it. Thank you

**Review by sagcatas — CHANGES_REQUESTED** [review]
conflict  fix your code looking like master branch

**Review by sagcatas — CHANGES_REQUESTED** [review]
change

**Pull request closed without merging**
