### PR TITLE
US02_gulten

### PR DESCRIPTION
**Pull request by Gultence**

### CODE REVIEW

**Comment by Gultence** [comment]
I have a mistake I am trying to fix it. Please review it.

**Comment by sagcatas** [comment]
please refactor names  both .feature and stepdefs
step1 - US02_RememberMe_StepDefs
step2 - US02_RememberMe.feature
step3 - if you have time we can do peer review quick and fix it quick

**Comment by Gultence** [comment]
Ok 👍 Sent from my iPhoneOn Mar 6, 2023, at 10:00 AM, Sagcatas ***@***.***> wrote:﻿
please refactor names  both .feature and stepdefs
step1 - US02_RememberMe_StepDefs
step2 - US02_RememberMe.feature
step3 - if you have time we can do peer review quick and fix it quick

**Comment by Gultence** [comment]
I have time for peer review. When do you available

**Review by sagcatas — APPROVED** [review]
It looks fine excepts some line differences 
If everybody update their master and fetch and update their branch it will be fine

**Pull request merged**
